//! Seaside Raceway's survey data, unpacked (port of
//! `src/levels/seaside/load.js`): the circuit, the ground round it and where
//! the aerial photo lies, all generated by `tools/seaside/build.py` from
//! OpenStreetMap, USGS 3DEP lidar and USGS NAIP photos.
//!
//! The JS reads `circuit.js` and `ground.js`; the port reads
//! `assets/seaside/survey.bin`, which the same script writes from the same
//! values (its format is in `Survey`'s docstring there). Decoding then
//! follows `load.js` step for step, including where it stores into a
//! `Float32Array` and where into a plain array.

use mp_math::js;

/// A point of a polyline, back in metres (the files hold decimetres).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Pt {
    pub x: f64,
    pub z: f64,
}

/// A polyline with its OSM name or kind.
#[derive(Clone, Debug, PartialEq)]
pub struct Named {
    pub name: String,
    pub pts: Vec<Pt>,
}

/// The centreline, every `step` metres from the start of the lap.
#[derive(Clone, Debug, PartialEq)]
pub struct Line {
    pub step: f64,
    pub n: usize,
    pub x: Vec<f64>,
    pub z: Vec<f64>,
    pub y: Vec<f64>,
    pub bank: Vec<f64>,
    pub hw: Vec<f64>,
    pub wall_l: Vec<f64>,
    pub wall_r: Vec<f64>,
    pub run_l: Vec<f64>,
    pub run_r: Vec<f64>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GridKind {
    Height,
    Rgb5,
    Cover,
}

/// A grid as f32 values (heights in metres, colour 0..1 per channel, cover
/// 0..1) with bilinear sampling in the local frame.
#[derive(Clone, Debug, PartialEq)]
pub struct Grid {
    pub x0: f64,
    pub z0: f64,
    pub step: f64,
    pub w: usize,
    pub h: usize,
    pub kind: GridKind,
    pub q: f64,
    pub ch: usize,
    pub values: Vec<f32>,
}

impl Grid {
    /// Sample at (x, z) into `out[0..ch]`; clamps at the edges. Returns how
    /// far inside the grid the point is (m, negative outside). `out` holds
    /// doubles, as a plain JS array does; a caller whose JS `out` is a
    /// `Float32Array` rounds with [`js::fround`].
    pub fn sample(&self, x: f64, z: f64, out: &mut [f64]) -> f64 {
        let (w, h) = (self.w as f64, self.h as f64);
        let x1 = self.x0 + (w - 1.0) * self.step;
        let z1 = self.z0 + (h - 1.0) * self.step;
        let mut gx = (x - self.x0) / self.step;
        let mut gz = (z - self.z0) / self.step;
        gx = if gx < 0.0 {
            0.0
        } else if gx > w - 1.001 {
            w - 1.001
        } else {
            gx
        };
        gz = if gz < 0.0 {
            0.0
        } else if gz > h - 1.001 {
            h - 1.001
        } else {
            gz
        };
        let (i, j) = (gx.floor(), gz.floor());
        let (tx, tz) = (gx - i, gz - j);
        let ch = self.ch;
        let k00 = (j as usize * self.w + i as usize) * ch;
        let k10 = k00 + ch;
        let k01 = k00 + self.w * ch;
        let k11 = k01 + ch;
        let d = |k: usize| self.values[k] as f64;
        for (c, o) in out.iter_mut().enumerate().take(ch) {
            let a = d(k00 + c) + (d(k10 + c) - d(k00 + c)) * tx;
            let b = d(k01 + c) + (d(k11 + c) - d(k01 + c)) * tx;
            *o = a + (b - a) * tz;
        }
        js::min_n(&[x - self.x0, x1 - x, z - self.z0, z1 - z])
    }

    fn decode(meta: &[f64], kind: GridKind, zlib: &[u8], base: f64) -> Result<Grid, String> {
        let [x0, z0, step, w, h, q] = meta else {
            return Err("survey: a grid needs six numbers".into());
        };
        let (w, h) = (*w as usize, *h as usize);
        let bytes = miniz_oxide::inflate::decompress_to_vec_zlib(zlib)
            .map_err(|e| format!("survey: inflating a grid: {e:?}"))?;
        let mut ch = 1;
        let values = match kind {
            GridKind::Height => {
                // Undo the 2D deltas: running sums down each column of the
                // row deltas, then along each row (int16 arithmetic).
                if bytes.len() < w * h * 2 {
                    return Err("survey: height grid too short".into());
                }
                let dd = |k: usize| i16::from_le_bytes([bytes[2 * k], bytes[2 * k + 1]]);
                let mut dx = vec![0i16; w * h];
                for i in 0..w {
                    let mut acc: i16 = 0;
                    for j in 0..h {
                        acc = acc.wrapping_add(dd(j * w + i));
                        dx[j * w + i] = acc;
                    }
                }
                let mut data = vec![0f32; w * h];
                for j in 0..h {
                    let mut acc: i16 = 0;
                    for i in 0..w {
                        acc = acc.wrapping_add(dx[j * w + i]);
                        data[j * w + i] = (base + acc as f64 * q) as f32;
                    }
                }
                data
            }
            GridKind::Rgb5 => {
                // Planar 5-bit channels → interleaved 0..1 (sRGB values; the
                // colouriser converts).
                ch = 3;
                let mut data = vec![0f32; w * h * 3];
                for c in 0..3 {
                    for k in 0..w * h {
                        data[k * 3 + c] = (bytes[c * w * h + k] as f64 / 31.0) as f32;
                    }
                }
                data
            }
            GridKind::Cover => (0..w * h)
                .map(|k| (bytes[k] as f64 / 255.0) as f32)
                .collect(),
        };
        Ok(Grid {
            x0: *x0,
            z0: *z0,
            step: *step,
            w,
            h,
            kind,
            q: *q,
            ch,
            values,
        })
    }
}

/// Where the draped aerial photo lies in the local frame (`photo.jpg`).
#[derive(Clone, Debug, PartialEq)]
pub struct Photo {
    pub file: String,
    pub x0: f64,
    pub z0: f64,
    pub x1: f64,
    pub z1: f64,
    pub w: f64,
    pub h: f64,
}

#[derive(Clone, Debug, PartialEq)]
pub struct SeasideData {
    /// UTM easting, northing and zone of the local frame's origin.
    pub origin: [f64; 3],
    /// Metres round the centreline.
    pub lap: f64,
    pub start_s: f64,
    pub line: Line,
    pub base: f64,
    pub height_fine: Grid,
    pub height_wide: Grid,
    pub color_fine: Grid,
    pub color_wide: Grid,
    pub trees_fine: Grid,
    pub trees_wide: Grid,
    /// Paved (0) or loose (1) ground, at 1 m round the lap.
    pub loose_grid: Grid,
    pub photo: Photo,
    pub pit_lane: Vec<Pt>,
    pub walls: Vec<Vec<Pt>>,
    pub grandstands: Vec<Vec<Pt>>,
    pub buildings: Vec<Named>,
    pub bridges: Vec<Named>,
    pub water: Vec<Vec<Pt>>,
    pub parking: Vec<Vec<Pt>>,
    pub paths: Vec<Named>,
}

/// Blend a fine grid into a wide one over the last `edge` metres of the
/// fine grid, so its border never shows as a step. The JS samples into
/// `Float32Array` scratch buffers (`a`, `b`) and writes into a plain array.
fn blended(fine: &Grid, wide: &Grid, edge: f64, x: f64, z: f64, out: &mut [f64]) {
    let ch = fine.ch;
    let mut a = [0f64; 3];
    let mut b = [0f64; 3];
    let inside = fine.sample(x, z, &mut a);
    for v in a.iter_mut().take(ch) {
        *v = js::fround(*v);
    }
    if inside >= edge {
        out[..ch].copy_from_slice(&a[..ch]);
        return;
    }
    wide.sample(x, z, &mut b);
    for v in b.iter_mut().take(ch) {
        *v = js::fround(*v);
    }
    let t = if inside <= 0.0 { 0.0 } else { inside / edge };
    let k = t * t * (3.0 - 2.0 * t);
    for c in 0..ch {
        out[c] = b[c] + (a[c] - b[c]) * k;
    }
}

impl SeasideData {
    pub fn height(&self, x: f64, z: f64) -> f64 {
        let mut out = [0.0];
        blended(&self.height_fine, &self.height_wide, 120.0, x, z, &mut out);
        out[0]
    }

    pub fn color(&self, x: f64, z: f64) -> [f64; 3] {
        let mut out = [0.0; 3];
        blended(&self.color_fine, &self.color_wide, 120.0, x, z, &mut out);
        out
    }

    pub fn trees(&self, x: f64, z: f64) -> f64 {
        let mut out = [0.0];
        blended(&self.trees_fine, &self.trees_wide, 120.0, x, z, &mut out);
        out[0]
    }

    /// Loose ground (dirt, grass) 1, paved 0; loose beyond the grid.
    pub fn loose(&self, x: f64, z: f64) -> f64 {
        let mut out = [0.0];
        if self.loose_grid.sample(x, z, &mut out) < 0.0 {
            1.0
        } else {
            out[0]
        }
    }

    /// Read `assets/seaside/survey.bin`.
    pub fn parse(bytes: &[u8]) -> Result<SeasideData, String> {
        let s = Sections::read(bytes)?;
        let line_i = |k: &str| s.i32(&format!("line.{k}"));
        let lx = line_i("x")?;
        let n = lx.len();
        let conv = |v: &[i32], f: &dyn Fn(f64) -> f64| {
            v.iter().map(|&x| f(x as f64)).collect::<Vec<f64>>()
        };
        let y0 = s.f64_1("line.y0")?;
        let line = Line {
            step: s.f64_1("line.step")?,
            n,
            x: conv(&lx, &|v| v / 100.0),
            z: conv(&line_i("z")?, &|v| v / 100.0),
            y: conv(&line_i("y")?, &|v| y0 + v / 100.0),
            bank: conv(&line_i("bank")?, &|v| v / 10000.0),
            hw: conv(&line_i("hw")?, &|v| v / 100.0),
            wall_l: conv(&line_i("wallL")?, &|v| v / 10.0),
            wall_r: conv(&line_i("wallR")?, &|v| v / 10.0),
            run_l: conv(&line_i("runL")?, &|v| v / 1000.0),
            run_r: conv(&line_i("runR")?, &|v| v / 1000.0),
        };
        let base = s.f64_1("base")?;
        let grid = |name: &str| -> Result<Grid, String> {
            let kind = match s.strs(&format!("{name}.kind"))?.first().map(String::as_str) {
                Some("height") => GridKind::Height,
                Some("rgb5") => GridKind::Rgb5,
                Some("cover") => GridKind::Cover,
                k => return Err(format!("survey: {name}: unknown kind {k:?}")),
            };
            Grid::decode(&s.f64(name)?, kind, s.bytes(&format!("{name}.data"))?, base)
        };
        let pts = |flat: &[i32]| {
            flat.as_chunks::<2>()
                .0
                .iter()
                .map(|p| Pt {
                    x: p[0] as f64 / 10.0,
                    z: p[1] as f64 / 10.0,
                })
                .collect::<Vec<Pt>>()
        };
        let polys = |name: &str| -> Result<Vec<Vec<Pt>>, String> {
            Ok(s.lists(name)?.iter().map(|l| pts(l)).collect())
        };
        let named = |name: &str, label: &str| -> Result<Vec<Named>, String> {
            let names = s.strs(&format!("{name}.{label}"))?;
            let lists = s.lists(&format!("{name}.pts"))?;
            Ok(names
                .into_iter()
                .zip(lists.iter())
                .map(|(name, l)| Named { name, pts: pts(l) })
                .collect())
        };
        let origin = s.f64("origin")?;
        let photo = s.f64("photo")?;
        Ok(SeasideData {
            origin: [origin[0], origin[1], origin[2]],
            lap: s.f64_1("lap")?,
            start_s: s.f64_1("startS")?,
            line,
            base,
            height_fine: grid("HEIGHT_FINE")?,
            height_wide: grid("HEIGHT_WIDE")?,
            color_fine: grid("COLOR_FINE")?,
            color_wide: grid("COLOR_WIDE")?,
            trees_fine: grid("TREES_FINE")?,
            trees_wide: grid("TREES_WIDE")?,
            loose_grid: grid("LOOSE")?,
            photo: Photo {
                file: s.strs("photo.file")?.into_iter().next().unwrap_or_default(),
                x0: photo[0],
                z0: photo[1],
                x1: photo[2],
                z1: photo[3],
                w: photo[4],
                h: photo[5],
            },
            pit_lane: pts(&s.i32("pitLane")?),
            walls: polys("walls")?,
            grandstands: polys("grandstands")?,
            buildings: named("buildings", "name")?,
            bridges: named("bridges", "kind")?,
            water: polys("water")?,
            parking: polys("parking")?,
            paths: named("paths", "kind")?,
        })
    }
}

enum Section<'a> {
    F64(Vec<f64>),
    I32(Vec<i32>),
    Bytes(&'a [u8]),
    Strs(Vec<String>),
    Lists(Vec<Vec<i32>>),
}

/// The file's sections, in file order.
struct Sections<'a>(Vec<(String, Section<'a>)>);

struct Reader<'a> {
    b: &'a [u8],
    p: usize,
}

impl<'a> Reader<'a> {
    fn take(&mut self, n: usize) -> Result<&'a [u8], String> {
        let end = self.p.checked_add(n).filter(|&e| e <= self.b.len());
        let end = end.ok_or("survey: file ends early")?;
        let out = &self.b[self.p..end];
        self.p = end;
        Ok(out)
    }
    fn u32(&mut self) -> Result<u32, String> {
        Ok(u32::from_le_bytes(self.take(4)?.try_into().unwrap()))
    }
    fn i32s(&mut self, n: usize) -> Result<Vec<i32>, String> {
        Ok(self
            .take(n * 4)?
            .as_chunks::<4>()
            .0
            .iter()
            .map(|c| i32::from_le_bytes(*c))
            .collect())
    }
    fn string(&mut self, n: usize) -> Result<String, String> {
        String::from_utf8(self.take(n)?.to_vec()).map_err(|e| format!("survey: {e}"))
    }
}

impl<'a> Sections<'a> {
    fn read(b: &'a [u8]) -> Result<Sections<'a>, String> {
        let mut r = Reader { b, p: 0 };
        if r.take(8)? != b"MRSURVEY" {
            return Err("survey: not a survey file".into());
        }
        let version = r.u32()?;
        if version != 1 {
            return Err(format!("survey: version {version}, expected 1"));
        }
        let count = r.u32()?;
        let mut out = Vec::new();
        for _ in 0..count {
            let len = r.take(1)?[0] as usize;
            let name = r.string(len)?;
            let kind = r.take(1)?[0];
            let n = r.u32()? as usize;
            let sec = match kind {
                1 => Section::F64(
                    r.take(n * 8)?
                        .as_chunks::<8>()
                        .0
                        .iter()
                        .map(|c| f64::from_le_bytes(*c))
                        .collect(),
                ),
                2 => Section::I32(r.i32s(n)?),
                3 => Section::Bytes(r.take(n)?),
                4 => {
                    let mut v = Vec::with_capacity(n);
                    for _ in 0..n {
                        let l = r.u32()? as usize;
                        v.push(r.string(l)?);
                    }
                    Section::Strs(v)
                }
                5 => {
                    let mut v = Vec::with_capacity(n);
                    for _ in 0..n {
                        let l = r.u32()? as usize;
                        v.push(r.i32s(l)?);
                    }
                    Section::Lists(v)
                }
                k => return Err(format!("survey: {name}: unknown section type {k}")),
            };
            out.push((name, sec));
        }
        Ok(Sections(out))
    }

    fn get(&self, name: &str) -> Result<&Section<'a>, String> {
        self.0
            .iter()
            .find(|(n, _)| n == name)
            .map(|(_, s)| s)
            .ok_or_else(|| format!("survey: no section {name}"))
    }
    fn f64(&self, name: &str) -> Result<Vec<f64>, String> {
        match self.get(name)? {
            Section::F64(v) => Ok(v.clone()),
            _ => Err(format!("survey: {name} is not f64")),
        }
    }
    fn f64_1(&self, name: &str) -> Result<f64, String> {
        self.f64(name)?
            .first()
            .copied()
            .ok_or_else(|| format!("survey: {name} is empty"))
    }
    fn i32(&self, name: &str) -> Result<Vec<i32>, String> {
        match self.get(name)? {
            Section::I32(v) => Ok(v.clone()),
            _ => Err(format!("survey: {name} is not i32")),
        }
    }
    fn bytes(&self, name: &str) -> Result<&'a [u8], String> {
        match self.get(name)? {
            Section::Bytes(v) => Ok(v),
            _ => Err(format!("survey: {name} is not bytes")),
        }
    }
    fn strs(&self, name: &str) -> Result<Vec<String>, String> {
        match self.get(name)? {
            Section::Strs(v) => Ok(v.clone()),
            _ => Err(format!("survey: {name} is not strings")),
        }
    }
    fn lists(&self, name: &str) -> Result<&Vec<Vec<i32>>, String> {
        match self.get(name)? {
            Section::Lists(v) => Ok(v),
            _ => Err(format!("survey: {name} is not lists")),
        }
    }
}
