// Seaside Raceway's survey data, unpacked: the circuit (circuit.js) and the
// ground round it (ground.js), both generated by tools/seaside/build.py from
// OpenStreetMap, USGS 3DEP lidar and USGS NAIP photos.
//
// load() is async (the grids are deflated) and runs once; everything it
// returns is plain arrays and functions, so the track and terrain builders
// can use it under Node as well as in the browser.

import * as C from './circuit.js';
import * as G from './ground.js';

function base64Bytes(s) {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

async function inflate(s) {
  const stream = new Blob([base64Bytes(s)]).stream().pipeThrough(new DecompressionStream('deflate'));
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

// A grid as Float32 values (heights in metres, colour 0..1 per channel,
// cover 0..1) with bilinear sampling in the local frame.
async function grid(spec) {
  const bytes = await inflate(spec.data);
  const { w, h } = spec;
  let data, ch = 1;
  if (spec.kind === 'height') {
    // Undo the 2D deltas: running sums down each column of the row deltas,
    // then along each row.
    const dd = new Int16Array(bytes.buffer, bytes.byteOffset, w * h);
    const dx = new Int32Array(w * h);
    for (let i = 0; i < w; i++) {
      let acc = 0;
      for (let j = 0; j < h; j++) { acc = (acc + dd[j * w + i]) << 16 >> 16; dx[j * w + i] = acc; }
    }
    data = new Float32Array(w * h);
    for (let j = 0; j < h; j++) {
      let acc = 0;
      for (let i = 0; i < w; i++) { acc = (acc + dx[j * w + i]) << 16 >> 16; data[j * w + i] = G.BASE + acc * spec.q; }
    }
  } else if (spec.kind === 'rgb5') {
    // Planar 5-bit channels → interleaved linear-ish 0..1 (sRGB values;
    // the colouriser converts).
    ch = 3;
    data = new Float32Array(w * h * 3);
    for (let c = 0; c < 3; c++) for (let k = 0; k < w * h; k++) data[k * 3 + c] = bytes[c * w * h + k] / 31;
  } else {
    data = new Float32Array(w * h);
    for (let k = 0; k < w * h; k++) data[k] = bytes[k] / 255;
  }
  const { x0, z0, step } = spec;
  const x1 = x0 + (w - 1) * step, z1 = z0 + (h - 1) * step;
  // Sample at (x, z) into out[0..ch-1]; clamps at the edges. Returns how
  // far inside the grid the point is (m, negative outside).
  const sample = (x, z, out) => {
    let gx = (x - x0) / step, gz = (z - z0) / step;
    gx = gx < 0 ? 0 : gx > w - 1.001 ? w - 1.001 : gx;
    gz = gz < 0 ? 0 : gz > h - 1.001 ? h - 1.001 : gz;
    const i = Math.floor(gx), j = Math.floor(gz), tx = gx - i, tz = gz - j;
    const k00 = (j * w + i) * ch, k10 = k00 + ch, k01 = k00 + w * ch, k11 = k01 + ch;
    for (let c = 0; c < ch; c++) {
      const a = data[k00 + c] + (data[k10 + c] - data[k00 + c]) * tx;
      const b = data[k01 + c] + (data[k11 + c] - data[k01 + c]) * tx;
      out[c] = a + (b - a) * tz;
    }
    return Math.min(x - x0, x1 - x, z - z0, z1 - z);
  };
  return { ...spec, data: null, values: data, sample };
}

// Blend a fine grid into a wide one over the last `edge` metres of the
// fine grid, so its border never shows as a step.
function blended(fine, wide, ch, edge) {
  const a = new Float32Array(ch), b = new Float32Array(ch);
  return (x, z, out) => {
    const inside = fine.sample(x, z, a);
    if (inside >= edge) { for (let c = 0; c < ch; c++) out[c] = a[c]; return out; }
    wide.sample(x, z, b);
    const t = inside <= 0 ? 0 : inside / edge;
    const k = t * t * (3 - 2 * t);
    for (let c = 0; c < ch; c++) out[c] = b[c] + (a[c] - b[c]) * k;
    return out;
  };
}

let cached = null;

export function load() {
  cached ??= (async () => {
    const [hf, hw, cf, cw, tf, tw] = await Promise.all([
      grid(G.HEIGHT_FINE), grid(G.HEIGHT_WIDE), grid(G.COLOR_FINE), grid(G.COLOR_WIDE), grid(G.TREES_FINE), grid(G.TREES_WIDE),
    ]);
    const hOut = [0], tOut = [0];
    const height = blended(hf, hw, 1, 120);
    const color = blended(cf, cw, 3, 120);
    const trees = blended(tf, tw, 1, 120);

    // The centreline, back in metres.
    const L = C.LINE, n = L.x.length;
    const line = {
      step: L.step, n,
      x: Float64Array.from(L.x, (v) => v / 100),
      z: Float64Array.from(L.z, (v) => v / 100),
      y: Float64Array.from(L.y, (v) => L.y0 + v / 100),
      bank: Float64Array.from(L.bank, (v) => v / 10000),
      wallL: Float64Array.from(L.wallL, (v) => v / 10),
      wallR: Float64Array.from(L.wallR, (v) => v / 10),
      runL: Float64Array.from(L.runL, (v) => v / 1000),
      runR: Float64Array.from(L.runR, (v) => v / 1000),
    };
    const pts = (flat) => { const out = []; for (let i = 0; i < flat.length; i += 2) out.push({ x: flat[i] / 10, z: flat[i + 1] / 10 }); return out; };
    return {
      origin: C.ORIGIN, lap: C.LAP, line,
      height: (x, z) => height(x, z, hOut)[0],
      color: (x, z, out = [0, 0, 0]) => color(x, z, out),
      trees: (x, z) => trees(x, z, tOut)[0],
      grids: { heightFine: hf, colorFine: cf, treesFine: tf, treesWide: tw },
      pitLane: pts(C.PIT_LANE),
      walls: C.WALLS.map(pts),
      grandstands: C.GRANDSTANDS.map(pts),
      buildings: C.BUILDINGS.map((b) => ({ name: b.name, pts: pts(b.pts) })),
      bridges: C.BRIDGES.map((b) => ({ kind: b.kind, pts: pts(b.pts) })),
      water: C.WATER.map(pts),
      parking: C.PARKING.map(pts),
      paths: C.PATHS.map((p) => ({ kind: p.kind, pts: pts(p.pts) })),
    };
  })();
  return cached;
}
