// The L2 golden for util/math.js (roadmap WP 1.1): mulberry32, hash2, the
// simplex noise, fbm and ridged, the small helpers, and the JS semantics of
// SPEC 4.2 (Math.round, Math.sign, Math.max/min, ToInt32), each evaluated
// over a fixed set of inputs with the parity kernel on. mp_math's tests
// (crates/mp_math/tests/golden.rs) require the same bits.
//
//   NODE_OPTIONS=--import=./tools/parity/kernel/register.mjs \
//     node tools/parity/math-golden.mjs [--check]
//
// Writes parity/golden/math/math.json. Every number is the hex of its f64
// bits, so nothing depends on decimal parsing. A long sequence is stored as
// its FNV-1a 64 hash (over the little-endian bits, as the traces hash) plus
// its first values, so a mismatch can be located. --check regenerates the
// file in memory and fails if it would change.

import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './lib/jstree.mjs';
import { fnv1a64, hashHex } from './lib/trace.mjs';
import { kernelInstalled } from '../../src/parity/kernel.js';
import {
  clamp, lerp, invLerp, smoothstep, damp, wrapAngle, DEG, stopSpeed,
  mulberry32, hash2, makeNoise2D, fbm, ridged,
} from '../../src/util/math.js';

if (!kernelInstalled()) {
  console.error('math-golden: run with NODE_OPTIONS=--import=./tools/parity/kernel/register.mjs');
  process.exit(1);
}

const OUT = path.join(ROOT, 'parity/golden/math/math.json');
const HEAD = 16; // values kept in full at the start of each sequence

const f64 = new Float64Array(1);
const u32 = new Uint32Array(f64.buffer);
const bits = (x) => { f64[0] = x; return u32[1].toString(16).padStart(8, '0') + u32[0].toString(16).padStart(8, '0'); };

// A sequence of doubles: its length, hash and first values.
// NaN is written as the one canonical NaN (0x7ff8000000000000), whatever
// bits the operation left, so the hash says only "NaN".
function seq(values) {
  values = values.map((v) => (Number.isNaN(v) ? NaN : v));
  const bytes = new Uint8Array(new Float64Array(values).buffer);
  return { n: values.length, hash: hashHex(fnv1a64(bytes)), head: values.slice(0, HEAD).map(bits) };
}

// Inputs shared by several sections: a deterministic spread of ordinary
// values, then the edges.
const EDGES = [
  0, -0, 0.5, -0.5, 1.5, -1.5, 2.5, -2.5, 0.49999999999999994, -0.49999999999999994,
  0.5000000000000001, -0.5000000000000001, 1e-300, -1e-300, 4503599627370495.5, -4503599627370495.5,
  4503599627370496, 9007199254740993, -9007199254740993, 2147483647.5, 2147483648, -2147483649, 4294967296.7,
  1e20, -1e20, Infinity, -Infinity, NaN, Math.PI, -Math.PI, 3 * Math.PI, -7.5, 1e4, 0.1, 0.2, 0.3,
];
const spread = (n, seed, scale) => {
  const r = mulberry32(seed);
  return Array.from({ length: n }, () => (r() * 2 - 1) * scale);
};
const ORDINARY = [...spread(2000, 11, 10), ...spread(2000, 12, 1000), ...spread(1000, 13, 1e7)];
const INPUTS = [...EDGES, ...ORDINARY];

const out = {
  note: 'Generated by tools/parity/math-golden.mjs with the parity kernel on. Do not edit. Values are hex f64 bits.',
  inputs: seq(INPUTS),
};

// ── JS semantics (SPEC 4.2) ─────────────────────────────────────────────
// Pairs for max and min: every edge against every edge, then ordinary pairs.
const pairs = [];
for (const a of EDGES) for (const b of EDGES) pairs.push([a, b]);
for (let i = 0; i + 1 < ORDINARY.length; i += 2) pairs.push([ORDINARY[i], ORDINARY[i + 1]]);
out.js = {
  round: seq(INPUTS.map(Math.round)),
  sign: seq(INPUTS.map(Math.sign)),
  max: seq(pairs.map(([a, b]) => Math.max(a, b))),
  min: seq(pairs.map(([a, b]) => Math.min(a, b))),
  max3: seq(pairs.map(([a, b]) => Math.max(a, b, a * 0.5))),
  min3: seq(pairs.map(([a, b]) => Math.min(a, b, a * 0.5))),
  toInt32: seq(INPUTS.map((x) => x | 0)),
  toUint32: seq(INPUTS.map((x) => x >>> 0)),
  imul: seq(pairs.map(([a, b]) => Math.imul(a, b))),
  fround: seq(INPUTS.map(Math.fround)),
  or: seq(INPUTS.map((x) => x || 7)),
  mod: seq(pairs.map(([a, b]) => a % b)),
};

// ── Helpers ─────────────────────────────────────────────────────────────
out.helpers = {
  DEG: bits(DEG),
  clamp: seq(INPUTS.map((x) => clamp(x, -1, 1))),
  clampVar: seq(pairs.map(([a, b]) => clamp(a, Math.min(b, 0), Math.max(b, 0)))),
  lerp: seq(pairs.map(([a, b]) => lerp(a, b, 0.3))),
  lerpT: seq(pairs.map(([a, b]) => lerp(-3, 8, a / (Math.abs(b) + 1)))),
  invLerp: seq(pairs.map(([a, b]) => invLerp(b, b + 10, a))),
  smoothstep: seq(pairs.map(([a, b]) => smoothstep(b, b + 25, a))),
  damp: seq(pairs.map(([a, b]) => damp(a, b, 4.5, 1 / 120))),
  dampLong: seq(pairs.map(([a, b]) => damp(a, b, Math.abs(b) % 50, Math.abs(a) % 2))),
  wrapAngle: seq(INPUTS.filter((x) => Number.isFinite(x) && Math.abs(x) < 1e6).map(wrapAngle)),
  stopSpeed: seq(pairs.map(([a, b]) => stopSpeed(a, Math.abs(b)))),
};

// ── mulberry32 ──────────────────────────────────────────────────────────
// Seeds as the callers pass them, including ones ToUint32 must wrap.
const SEEDS = [0, 1, 7, 42, 99, 0x9e3779b9, 4294967295, -1, 3.7, 2 ** 33 + 5, -123456789.9,
  (1 + 0x9e3779b9 * 1) >>> 0, (1 + 0x9e3779b9 * 2) >>> 0, (1 + 0x9e3779b9 * 3) >>> 0];
out.mulberry32 = SEEDS.map((seed) => {
  const r = mulberry32(seed);
  return { seed: bits(seed), draws: seq(Array.from({ length: 100000 }, () => r())) };
});

// ── hash2 ───────────────────────────────────────────────────────────────
const h2 = [];
for (const seed of [0, 3, 9, 11, 2147483647]) {
  for (let i = -60; i <= 60; i++) for (let j = -60; j <= 60; j++) h2.push(hash2(i, j, seed));
}
const h2odd = [];
for (let i = 0; i + 2 < INPUTS.length; i += 3) h2odd.push(hash2(INPUTS[i], INPUTS[i + 1], INPUTS[i + 2]));
h2odd.push(hash2(5, 9)); // the default seed
out.hash2 = { grid: seq(h2), odd: seq(h2odd) };

// ── Noise ───────────────────────────────────────────────────────────────
// Points from small to very large coordinates (where `i & 255` wraps
// through ToInt32), and the terrain's typical scales.
const pts = [];
{
  const r = mulberry32(5);
  for (let k = 0; k < 4000; k++) pts.push([(r() * 2 - 1) * 50, (r() * 2 - 1) * 50]);
  for (let k = 0; k < 3000; k++) pts.push([(r() * 2 - 1) * 5000, (r() * 2 - 1) * 5000]);
  for (let k = 0; k < 1000; k++) pts.push([(r() * 2 - 1) * 3e9, (r() * 2 - 1) * 3e9]);
  for (let k = 0; k < 1000; k++) pts.push([(r() * 2 - 1) * 1e16, (r() * 2 - 1) * 1e16]);
  for (let k = -20; k <= 20; k++) pts.push([k, k * 0.5], [k * 0.25, -k]);
}
out.noise = [1, 5, 7, 99, 108, 313].map((seed) => {
  const n = makeNoise2D(seed);
  const at = (f) => seq(pts.map(([x, y]) => f(x, y)));
  return {
    seed,
    noise: at(n),
    fbm: at((x, y) => fbm(n, x / 90, y / 90)),
    fbm3: at((x, y) => fbm(n, x / 380, y / 380, 3)),
    fbm2: at((x, y) => fbm(n, x / 40 + 9, y / 40, 2, 2.0, 0.5)),
    fbmOdd: at((x, y) => fbm(n, x / 70, y / 70, 4, 1.9, 0.55)),
    ridged: at((x, y) => ridged(n, x / 1700 + 9.1, y / 1700)),
    ridged4: at((x, y) => ridged(n, x / 1500 + 4.2, y / 1500, 4)),
    ridgedOdd: at((x, y) => ridged(n, x / 1900 + 3.3, y / 1900, 5, 2.0, 0.45)),
  };
});
out.noiseDefault = seq(pts.map(([x, y]) => makeNoise2D()(x, y)));

const text = JSON.stringify(out, null, 1) + '\n';
if (process.argv.includes('--check')) {
  const old = fs.readFileSync(OUT, 'utf8');
  if (old !== text) {
    console.error('math-golden: regenerated file differs from', path.relative(ROOT, OUT));
    process.exit(1);
  }
  console.log('math-golden: identical');
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, text);
  console.log('math-golden: wrote', path.relative(ROOT, OUT), `(${text.length} bytes)`);
}
