// Which scenery module registered what in World.build's plan stage, so a
// level can be built with some modules ported and the rest replayed from
// the recordings, in the JS order (DECISIONS D330).
//
//   NODE_OPTIONS=--import=./tools/parity/kernel/register.mjs \
//     node tools/parity/scenery-plan.mjs [--check]
//
// tools/parity/terrain-plan.mjs records every level's flattens, carves and
// railway bed (parity/golden/terrain/<level>.json) and road-plan.mjs the
// fence gaps, unpainted stretches and runout (parity/golden/road/), each as
// one list in registration order. This tool runs the same plan stage under
// Node with the parity kernel (the Track, `new Terrain`, each scenery module
// made as loadScenery makes it and its plan() run) and notes, around each
// module's plan(), how far each list had grown: module k registered
// flattens [a, b) of the recording, and so on. mp_worldgen's
// `scenery::RecordedScenery` replays a module from its slices, so a ported
// module's real plan() runs in its own place between recorded ones.
//
// Writes parity/golden/scenery-plan/<level>.json. The totals must equal the
// terrain and road goldens' lists (checked here and in the Rust tests).
// --check regenerates in memory and fails if a file would change.

import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './lib/jstree.mjs';
import { seedRandom, RANDOM_SEED } from './lib/seed-random.mjs';
import { kernelInstalled } from '../../src/parity/kernel.js';

if (!kernelInstalled()) {
  console.error('scenery-plan: run with NODE_OPTIONS=--import=./tools/parity/kernel/register.mjs');
  process.exit(1);
}
seedRandom(RANDOM_SEED);

await import('../../test/unit/support/three.js');
const { LEVELS } = await import('../../test/unit/support/levels.js');
const { Track } = await import('../../src/track/Track.js');
const { Terrain } = await import('../../src/world/Terrain.js');

const check = process.argv.includes('--check');
const OUT = path.join(ROOT, 'parity/golden/scenery-plan');
const IDS = ['sierra', 'coast', 'streets', 'desert', 'seaside', 'cruise'];

const f64 = new Float64Array(1);
const u32 = new Uint32Array(f64.buffer);
const bits = (x) => { f64[0] = x; return u32[1].toString(16).padStart(8, '0') + u32[0].toString(16).padStart(8, '0'); };

let problems = 0;
fs.mkdirSync(OUT, { recursive: true });
for (const id of IDS) {
  const level = LEVELS.find((l) => l.id === id);
  const track = new Track(level);
  const terrain = new Terrain(track, level);
  const world = { level, track, terrain, zoneIndex: (key) => level.zones.findIndex((z) => z.key === key) };
  const names = [...new Set(level.zones.map((z) => z.scenery).filter(Boolean))];
  const counts = () => ({
    flattens: terrain.flattens.length,
    carves: terrain.carves.length,
    fenceGaps: (track.fenceGaps || []).length,
    noMarks: (track.noMarks || []).length,
    rail: terrain.desertRail,
    runout: track.runout,
  });
  const modules = [];
  for (const name of names) {
    const mod = await import(`../../src/world/${name}.js`);
    const zone = level.zones.findIndex((z) => z.scenery === name);
    const s = new mod.default({ zone, key: level.zones[zone].key, level });
    const a = counts();
    let failed = null;
    try { s.plan?.(world); } catch (e) { failed = e.message; }
    const b = counts();
    modules.push({
      name, zone, key: level.zones[zone].key, label: s.label ?? null,
      failed,
      flattens: [a.flattens, b.flattens],
      carves: [a.carves, b.carves],
      fenceGaps: [a.fenceGaps, b.fenceGaps],
      noMarks: [a.noMarks, b.noMarks],
      // Whether this module set Desert's railway bed.
      desertRail: b.rail !== a.rail,
      // track.runout after this module's plan(), where it changed it.
      runout: Object.is(a.runout, b.runout) ? null : bits(b.runout),
    });
  }
  // The totals are the recordings' lists.
  const tg = JSON.parse(fs.readFileSync(path.join(ROOT, 'parity/golden/terrain', id + '.json'), 'utf8'));
  const rg = JSON.parse(fs.readFileSync(path.join(ROOT, 'parity/golden/road', id + '.json'), 'utf8'));
  const c = counts();
  const ok = c.flattens === tg.flattens.length && c.carves === tg.carves.length
    && c.fenceGaps === rg.fenceGaps.length && c.noMarks === rg.noMarks.length
    && bits(c.runout) === rg.runout && !!c.rail === (tg.desertRail !== null);
  if (!ok) problems++;
  console.log(`${id}: ${modules.map((m) => `${m.name} [${m.flattens}] [${m.carves}] [${m.fenceGaps}] [${m.noMarks}]${m.runout ? ' runout' : ''}${m.desertRail ? ' rail' : ''}`).join('; ')}; ${ok ? 'totals equal the terrain and road goldens' : 'TOTALS DIFFER from the terrain and road goldens'}`);
  const out = {
    note: 'Generated by tools/parity/scenery-plan.mjs with the parity kernel on. Do not edit. Ranges index parity/golden/terrain/<level>.json (flattens, carves) and parity/golden/road/<level>.json (fenceGaps, noMarks); runout is hex f64 bits.',
    level: id,
    modules,
  };
  const file = path.join(OUT, id + '.json');
  const text = JSON.stringify(out, null, 1) + '\n';
  if (check) {
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== text) { console.error(`${path.relative(ROOT, file)}: would change`); problems++; }
  } else fs.writeFileSync(file, text);
}
if (problems) { console.error(`scenery-plan: ${problems} problem(s)`); process.exit(1); }
