// The L2 golden for Seaside Raceway's survey data (roadmap WP 1.2): the
// centreline and the ground functions as src/levels/seaside/load.js
// decodes them from circuit.js and ground.js, which mp_levels::seaside must
// reproduce from assets/seaside/survey.bin. Taken with the parity kernel on
// (nothing here calls it, but every golden is).
//
//   NODE_OPTIONS=--import=./tools/parity/kernel/register.mjs \
//     node tools/parity/seaside-golden.mjs [--check]
//
// Writes parity/golden/seaside/survey.json in the format of the math golden
// (math-golden.mjs): sequences as FNV-1a 64 of their f64 bits plus the first
// values in hex.

import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './lib/jstree.mjs';
import { fnv1a64, hashHex } from './lib/trace.mjs';
import { kernelInstalled } from '../../src/parity/kernel.js';
import { mulberry32 } from '../../src/util/math.js';
import { load } from '../../src/levels/seaside/load.js';

if (!kernelInstalled()) {
  console.error('seaside-golden: run with NODE_OPTIONS=--import=./tools/parity/kernel/register.mjs');
  process.exit(1);
}

const OUT = path.join(ROOT, 'parity/golden/seaside/survey.json');
const HEAD = 16;
const f64 = new Float64Array(1);
const u32 = new Uint32Array(f64.buffer);
const bits = (x) => { f64[0] = x; return u32[1].toString(16).padStart(8, '0') + u32[0].toString(16).padStart(8, '0'); };
function seq(values) {
  values = Array.from(values, (v) => (Number.isNaN(v) ? NaN : v));
  const bytes = new Uint8Array(new Float64Array(values).buffer);
  return { n: values.length, hash: hashHex(fnv1a64(bytes)), head: values.slice(0, HEAD).map(bits) };
}

const D = await load();
const out = {
  note: 'Generated by tools/parity/seaside-golden.mjs with the parity kernel on. Do not edit. Values are hex f64 bits.',
  origin: [D.origin.utmE, D.origin.utmN, D.origin.zone].map(bits),
  lap: bits(D.lap),
  line: Object.fromEntries(['x', 'z', 'y', 'bank', 'hw', 'wallL', 'wallR', 'runL', 'runR'].map((k) => [k, seq(D.line[k])])),
  photo: [D.photo.x0, D.photo.z0, D.photo.x1, D.photo.z1].map(bits),
  grids: Object.fromEntries(Object.entries(D.grids).map(([k, g]) => [k, { w: g.w, h: g.h, x0: bits(g.x0), z0: bits(g.z0), values: seq(g.values) }])),
  loose: { w: D.photo.loose.w, h: D.photo.loose.h, values: seq(D.photo.loose.values) },
  pitLane: seq(D.pitLane.flatMap((p) => [p.x, p.z])),
  walls: seq(D.walls.flatMap((w) => w.flatMap((p) => [p.x, p.z]))),
  buildings: D.buildings.map((b) => b.name),
  paths: D.paths.map((b) => b.kind),
};

// The samplers over the whole wide grid, the fine grid's blend band and
// the circuit's surroundings (where the physics reads the loose mask).
const pts = [];
{
  const r = mulberry32(17);
  for (let k = 0; k < 6000; k++) pts.push([(r() * 2 - 1) * 4000, (r() * 2 - 1) * 4000]);
  for (let k = 0; k < 6000; k++) pts.push([(r() * 2 - 1) * 1100, (r() * 2 - 1) * 1100]);
  for (let s = 0; s < D.line.n; s += 3) {
    for (const lat of [-30, -18, -9, 9, 18, 30]) {
      const i = s, j = (s + 1) % D.line.n;
      const dx = D.line.x[j] - D.line.x[i], dz = D.line.z[j] - D.line.z[i], l = Math.hypot(dx, dz);
      pts.push([D.line.x[i] - (dz / l) * lat, D.line.z[i] + (dx / l) * lat]);
    }
  }
}
out.points = seq(pts.flat());
out.height = seq(pts.map(([x, z]) => D.height(x, z)));
out.color = seq(pts.flatMap(([x, z]) => D.color(x, z)));
out.trees = seq(pts.map(([x, z]) => D.trees(x, z)));
out.loose = { ...out.loose, at: seq(pts.map(([x, z]) => D.loose(x, z))) };

const text = JSON.stringify(out, null, 1) + '\n';
if (process.argv.includes('--check')) {
  if (fs.readFileSync(OUT, 'utf8') !== text) {
    console.error('seaside-golden: regenerated file differs from', path.relative(ROOT, OUT));
    process.exit(1);
  }
  console.log('seaside-golden: identical');
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, text);
  console.log('seaside-golden: wrote', path.relative(ROOT, OUT), `(${text.length} bytes)`);
}
