// The fuzz baseline (roadmap WP 0.4, SPEC 4.6 test 5): random controls on
// every level, in the real game (headless Chrome, every parity hook on,
// ?fuzz=N in place of the autopilot), measuring how far any body gets
// outside the walls. Collisions can push a body past a wall for a tick in
// the JS too, so the Rust fuzz test is held to what the JS reaches under the
// same fuzz, not to zero.
//
//   node tools/parity/sim-fuzz.mjs
//
// Writes parity/golden/sim/fuzz.json. Each run also fails if a position or
// speed stops being finite.
//
// Excursion of a body at a tick: max(lat + halfW - wallR, -lat + halfW -
// wallL) on the road frame at its s. Bodies: the player, the rivals, traffic
// on our carriageway (not the far one, which has no walls of ours), police
// units and roadblock cars. Not sawhorses (debris flies).

import fs from 'node:fs';
import path from 'node:path';
import { launch, openGame } from '../../test/e2e/harness.js';
import { ROOT, jsTreeKey } from './lib/jstree.mjs';

const TICKS = 3 * 60 * 120;
const RUNS = [
  ...['sierra', 'coast', 'streets', 'desert', 'seaside', 'cruise'].map((level) => ({ id: `${level}-race`, level, pursuit: 0 })),
  ...['sierra', 'coast', 'streets', 'desert'].map((level) => ({ id: `${level}-pursuit`, level, pursuit: 3 })),
];
const FUZZ_SEED = 1;

const queryFor = (r) => `parity=1&seed=1&fuzz=${FUZZ_SEED}&ticks=16&level=${r.level}&autostart=sports&${r.pursuit ? `pursuit=1&heat=${r.pursuit}` : 'pursuit=0'}`;

function fuzzInit(ticks) {
  const st = { tick: 0, done: false, error: null, max: {}, where: {} };
  window.__fz = st;
  let parity;
  Object.defineProperty(window, '__parity', {
    configurable: true,
    get: () => parity,
    set(p) {
      parity = p;
      p.onTick = (race) => {
        if (st.done || st.error) return;
        try {
          st.tick++;
          const t = race.track;
          const note = (cls, b, lat, s, halfW) => {
            const f = t.frame(s);
            const e = Math.max(lat + halfW - f.wallR, -lat + halfW - f.wallL);
            if (!(e <= (st.max[cls] ?? -Infinity))) { st.max[cls] = e; st.where[cls] = { tick: st.tick, s, lat, name: b }; }
          };
          const v = race.player;
          for (const k of ['x', 'y', 'z', 'vx', 'vz', 'yaw', 's', 'lat']) if (!Number.isFinite(v[k])) throw new Error(`player.${k} = ${v[k]}`);
          note('player', 'player', v.lat, v.s, v.halfW);
          race.ais.forEach((a, i) => note('rivals', a.name, a.lat, a.s, a.v.halfW));
          race.traffic.cars.forEach((c, i) => { if (c.active && !c.opposite) note('traffic', `traffic ${i} ${c.kindName}`, c.lat, c.s, c.v.halfW); });
          const pu = race.pv?.pursuit;
          if (pu) [...pu.units, ...pu.blockCars].forEach((u, i) => { if (u.active) note('police', `police ${i} ${u.mode}`, u.lat, u.s, u.v.halfW); });
          for (const c of [...race.ais, ...race.traffic.cars, ...(pu ? [...pu.units, ...pu.blockCars] : [])]) {
            if (!Number.isFinite(c.s) || !Number.isFinite(c.lat) || !Number.isFinite(c.speed)) throw new Error('a body went non-finite');
          }
          if (p.errors.length) throw new Error('the main loop caught: ' + p.errors[0]);
          if (st.tick >= ticks) st.done = true;
        } catch (e) { st.error = String(e.stack || e); }
      };
    },
  });
}

const browser = await launch();
const out = { note: 'Generated by tools/parity/sim-fuzz.mjs. Max excursion outside the walls, metres, per class of body.', ticks: TICKS, fuzzSeed: FUZZ_SEED, jsTree: jsTreeKey(), runs: {} };
try {
  for (const r of RUNS) {
    const t0 = Date.now();
    const g = await openGame(browser, { query: queryFor(r), init: fuzzInit, initArgs: [TICKS] });
    await g.waitFor(() => window.__fz.done || window.__fz.error || false, { timeout: 20 * 60 * 1000, interval: 500, what: r.id });
    const st = await g.eval(() => window.__fz);
    if (st.error) throw new Error(`${r.id}: ${st.error}`);
    if (g.errors.length) throw new Error(`${r.id}: page errors: ${g.errors.join(' | ')}`);
    await g.close();
    out.runs[r.id] = { query: queryFor(r), max: st.max, where: st.where };
    console.log(`${r.id}: ${Object.entries(st.max).map(([k, v]) => `${k} ${v.toFixed(3)}`).join(', ')} (${((Date.now() - t0) / 1000).toFixed(0)} s)`);
  }
} finally {
  await browser.close();
}
const file = path.join(ROOT, 'parity/golden/sim/fuzz.json');
fs.writeFileSync(file, JSON.stringify(out, null, 1) + '\n');
console.log('wrote ' + path.relative(ROOT, file));
