// What the simulation needs from the JS world, which scenery code computes
// rather than the level files (roadmap WP 0.4, SPEC 4.3): the road's runout
// past the finish, the opposite carriageway's range, lanes and height
// samples, and every vehicle's dimensions (CarModel.js) as the game uses
// them. Taken with the kernel on, from a race started on each level (in Hot
// Pursuit where the level has police, so the police cars and sawhorses are
// built too).
//
//   node tools/parity/sim-world.mjs [--check]
//
// Writes parity/golden/sim/world-data.json. --check regenerates it and
// fails if the file would change.

import fs from 'node:fs';
import path from 'node:path';
import { launch, openGame } from '../../test/e2e/harness.js';
import { ROOT } from './lib/jstree.mjs';

const LEVELS = ['sierra', 'coast', 'streets', 'desert', 'seaside', 'cruise'];
const POLICE = new Set(['sierra', 'coast', 'streets', 'desert']);

function readWorld() {
  const w = window.__world, t = w.track, r = window.__race;
  const oc = w.oppositeCarriageway;
  const dimsOf = (v) => ({ ...v.model.dims, halfW: v.halfW, halfL: v.halfL, mass: v.mass });
  const out = {
    track: { length: t.length, n: t.n, loop: !!t.loop, laps: t.laps ?? null, startS: t.startS, finishS: t.finishS, runout: t.runout, roadEnd: t.loop ? null : t.roadEnd },
    oppositeCarriageway: oc ? {
      s0: oc.s0, s1: oc.s1, lanes: oc.lanes, dir: oc.dir,
      // The height is ported as its formula (city/freeway.js oppY); these
      // samples check the port.
      ySamples: Array.from({ length: 11 }, (_, i) => { const s = oc.s0 + (oc.s1 - 1 - oc.s0) * i / 10; return [s, oc.y(s)]; }),
    } : null,
    bodies: {
      player: { kind: r.player.kind, ...dimsOf(r.player) },
      rivals: r.ais.map((a) => ({ kind: a.v.kind, name: a.name, ...dimsOf(a.v) })),
      traffic: r.traffic.cars.map((c) => ({ kind: c.kindName, opposite: c.opposite, ...dimsOf(c.v) })),
      police: r.pv ? [...r.pv.pursuit.units, ...r.pv.pursuit.blockCars].map((u) => ({ type: u.type, kind: u.v.kind, ...dimsOf(u.v) })) : [],
      sawhorses: r.pv ? r.pv.pursuit.sawhorses.map((b) => ({ kind: b.v.kind, ...dimsOf(b.v) })) : [],
    },
  };
  return out;
}

async function allKinds() {
  const { buildVehicle, VEHICLE_KINDS } = await import('/src/vehicles/CarModel.js');
  const out = {};
  for (const k of VEHICLE_KINDS) {
    out[k] = {
      default: buildVehicle(k, {}).dims,
      high: buildVehicle(k, { lod: 'high' }).dims,
      lowFar: buildVehicle(k, { lod: 'low', far: true }).dims,
    };
  }
  return out;
}

async function capture() {
  const browser = await launch();
  const data = { note: 'Generated by tools/parity/sim-world.mjs with the parity kernel on. Do not edit.', levels: {}, kinds: null };
  try {
    for (const id of LEVELS) {
      const q = `kernel=1&level=${id}&autostart=sports&${POLICE.has(id) ? 'pursuit=1' : 'pursuit=0'}`;
      const g = await openGame(browser, { query: q });
      await g.waitFor(() => window.__race && window.__race.traffic && true, { timeout: 60000, what: 'the race' });
      data.levels[id] = await g.eval(readWorld);
      if (!data.kinds) data.kinds = await g.eval(allKinds);
      if (g.errors.length) throw new Error(`${id}: page errors: ${g.errors.join(' | ')}`);
      await g.close();
    }
  } finally {
    await browser.close();
  }
  return JSON.stringify(data, null, 1) + '\n';
}

const file = path.join(ROOT, 'parity/golden/sim/world-data.json');
const text = await capture();
if (process.argv.includes('--check')) {
  const old = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (old !== text) { console.error('world-data.json differs from a fresh capture'); process.exit(1); }
  console.log('world-data.json: reproduced exactly');
} else {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
  console.log(`wrote ${path.relative(ROOT, file)} (${(text.length / 1024).toFixed(0)} KB)`);
}
