// The JS simulation's speed (roadmap WP 0.4, SPEC 4.6 test 6): ticks per
// second for a full Sierra field (the player on the autopilot, the five
// rivals, 22 traffic cars, collisions), stepped in Node as the module oracle
// steps it (tools/parity/lib/node-sim.mjs, scenario full-field-sierra), with
// no trace recording. The Rust simulation must not be slower (M1.7). Race's
// own rules are not included: in the game they share Race.update with the
// presentation and cannot be timed apart.
//
//   node tools/parity/sim-bench.mjs              (writes the baseline)
//
// Runs the field twice in child processes, once with V8's Math and once with
// the parity kernel (wasm calls cost something), and writes
// parity/golden/sim/bench.json with the machine it ran on.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(here), '../..');
const TICKS = 120 * 120; // two minutes of race
const REPEATS = 5;

if (process.argv[2] === '--child') {
  // Inside a child: the kernel is installed or not by NODE_OPTIONS. node-sim
  // insists on the kernel, so without it import the pieces directly.
  if (!Math.__kernel) Object.defineProperty(Math, '__kernel', { value: true, configurable: true }); // let node-sim load
  const S = await import('./lib/node-sim.mjs');
  const run = () => {
    const { L, t, world } = S.level('sierra');
    const streams = S.simStreams(1);
    const P = S.player(t, 'sports');
    const ais = S.rivals(L, t, streams.ai);
    S.grid(t, P, ais);
    const traf = S.traffic(L, t, world, 22, streams.traffic);
    const sim = new S.Sim({ t, P, ais, traf, streams });
    const idle = () => ({ steer: 0, throttle: 0, brake: 0, handbrake: false, nitro: false, analog: false });
    const t0 = process.hrtime.bigint();
    for (let k = 0; k < TICKS; k++) sim.step(S.quantiseInput(S.autopilot(idle(), P.v, t)));
    return Number(process.hrtime.bigint() - t0) / 1e9;
  };
  run(); // warm up
  const times = Array.from({ length: REPEATS }, run).sort((a, b) => a - b);
  console.log(JSON.stringify({ ticksPerSecond: Math.round(TICKS / times[Math.floor(REPEATS / 2)]), best: Math.round(TICKS / times[0]) }));
} else {
  const child = (kernel) => JSON.parse(execFileSync(process.execPath, [here, '--child'], {
    cwd: ROOT, encoding: 'utf8',
    env: { ...process.env, NODE_OPTIONS: kernel ? '--import=./tools/parity/kernel/register.mjs' : '' },
  }));
  const v8 = child(false), kernel = child(true);
  const out = {
    note: 'Generated by tools/parity/sim-bench.mjs: ticks per second (median of 5 runs of 14,400 ticks) for a full Sierra field in Node. Machine-dependent: compare Rust on the same machine.',
    field: 'player (sports, autopilot) + 5 rivals + 22 traffic cars + collisions; no Race rules, no trace',
    v8Math: v8, parityKernel: kernel,
    machine: { cpu: os.cpus()[0].model, cores: os.cpus().length, node: process.version, platform: `${os.platform()} ${os.release()}`, loadAverage: +os.loadavg()[0].toFixed(1) },
    date: new Date().toISOString().slice(0, 10),
  };
  fs.writeFileSync(path.join(ROOT, 'parity/golden/sim/bench.json'), JSON.stringify(out, null, 1) + '\n');
  console.log(`V8 Math: ${v8.ticksPerSecond} ticks/s; parity kernel: ${kernel.ticksPerSecond} ticks/s`);
}
